# Generated by Django 3.2.9 on 2022-10-03 00:33

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('home', models.CharField(blank=True, max_length=200, null=True)),
                ('info', jsonfield.fields.JSONField(default={'posts': []})),
            ],
        ),
    ]
