# Generated by Django 3.2.9 on 2022-10-04 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_rename_home_mainadmin_group_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='mainadmin',
            name='group_home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.grouphome'),
        ),
    ]
