# Generated by Django 3.2.9 on 2022-10-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20221004_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouphome',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
