# Generated by Django 3.2.9 on 2022-10-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_mainadmin_group_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainadmin',
            name='group_home',
        ),
        migrations.AddField(
            model_name='mainadmin',
            name='group_home',
            field=models.ManyToManyField(blank=True, null=True, to='Main.GroupHome'),
        ),
    ]
