# Generated by Django 4.1.2 on 2022-10-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20221004_0419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainAdmin',
            new_name='NameObject',
        ),
    ]
